# 빅데이터개론2 - 중간고사의 범위와 요약 

다음은 중간고사의 범위에 해당하는 주제와 내용을 요약, 정리한 것입니다. 

In [1]:
import math
import sys
import numpy as np
import pandas as pd

## 중간고사 시험 범위

[온라인 교재](https://uos-bigdata.github.io/bigdatabook/intro.html)에서 다음 내용이 중간고사 시험범위입니다.

- 2장. 파이썬의 기초
- 3장. 자료의 형식
- 4장. 데이터프레임
- 5장 1절. 자료의 분포

**5장 1절의 내용 중 그림이나 그래프를 그리는 파이썬 코드는 시험에 출제되지 않습니다. 자료를 이용한 여러가지 통계량의 계산과 그레프를 이용하여 자료의 분포를 파학하는 문제가 출제됩니다.** 

[빅데이터 개론 2 - 연습 및 과제 해답](https://uos-bigdata.github.io/bigdata-exercise/intro.html)은 교과서, 강의, 과제 등에서 다룬 주제들에 대한 연습과 답안을 제공하는 노트북이 있는 사이트입니다. 꼭 참고하세요.  

## 자료의 분포

- 그림을 이용한 분포의 특성 분석

  - 파이 차트(pie chart)와 바 차트(bar chart): 범주형 자료에 대한 분포의 특성  
  - 히스토그램과 상자그림: 연속형 자료에 대한 분포의 특성
  - 시계열 그림: 시간에 따른 변화
  - 산점도(산포도) : 두 개의 연속형 분포의 관계

- 연속형 자료에 대한 요약통계량(평균, 표준편차, 중간값, Q1, Q3, 최대값, 최소값)의 정의와 의미


## 파이썬 프로그래밍 

### 표현식과 변수

- 연산자

  - 산술 연산자 
    + `+`, `-`, `*`, `/`, `**`, `//`

  - 비교 연산자
    + `==`, `<`, `>`, `>=`, `<=`

  - 논리 연산자
    + `and`, `or`, `not`

  비교 연산자와 논리 연산자의 결과는 `True` 또는 `False` 이며 이 결과는 예약어이다.

-변수의 지정과 이름의 규칙 

  - 대, 소문자를 구분한다
  - 문자, 숫자, 언더바(_)를 포함할 수 있다. 하지만 숫자로 시작하면 안 된다.
  - 변수의 값은 `variable = ... ` 으로 지정한다.



### 문자열

- 문자열로 정의된 변수(이름)을 더하기 `+` 연산자로 조합하여 여러 개의 문자열을 연결
- 문자열을 정수로 곱하면 숫자만큼 반복 
- 문자열에서 원하는 문자열의 위치를 지정해 주면 문자열의 일부분만 추출 (예: `string[0]`, `string[1:2]`)
- 특수한 기능을 가진 특수 문자열 (예: `\n`)
- 문장열에 작은 따옴표 `'` 와 큰 따옴표 `"` 가 포함된 경우 출력 방법
- 문자열에 대한 메소드(method)
  + `string.replce()`
  + `string.upper()`
  + `string.count()`
  + `string.split()`

In [2]:
color = 'red'

In [3]:
thing = "apple"

In [4]:
color + ' ' + thing

'red apple'

In [5]:
thing*3

'appleappleapple'

In [6]:
thing[0]

'a'

In [7]:
thing[0:2]

'ap'

In [8]:
print("가나다\n라마바사")

가나다
라마바사


In [9]:
print("He said \"yes\"")

He said "yes"


In [10]:
directory_path = r'C:\some\name'
directory_path

'C:\\some\\name'

문자열도 서로 비교할 수 있다. 문자는 순서가 있으며 영문은 알파벳의 순서로, 한글은 자음의 순서로 위치가 결정된다.

- 문자의 순서는 숫자, 영문 대문자, 영문 소문자, 한글의 순으로 나타난다.

```
1 < 2 < 3 < ..... < A < B < C <......< X < Y < Z < a < b < c < ..... < x < y < z < 가 < 나 < 다 < ...
```

- 하나의 문자를 비교하는 경우 주어진 순서에 따라서 **앞에 위치한 문자가  뒤에 위치한 문자보다 크기가 작다** 

- 문자열의 비교는 대응되는 위치의 문자를 비교하여 대소가 결정된다. 

In [11]:
'A' < 'B'

True

In [21]:
'x' > 'y'

False

In [20]:
'가' > '나'

False

In [22]:
'가' > '거'

False

In [12]:
'AZ' > 'BA'

False

In [26]:
'1' < 'A'

True

In [27]:
'999999' < 'A'

True

다음 두 문자열을 비교하는 경우 3번째 위치(`abc`)까지 동일하고 4번째 위치한 `d` 와 `c` 를 비교하므로 결과는 `False` 이다. 

In [15]:
'abcd' < 'abcc'

False

In [19]:
'abc' < 'abcd'

True

In [16]:
'시립대' < '시립대학교'

True

In [25]:
'가' < '값'

True

영문자에서 대문자가 소문자보다 앞에 위치한다. 

In [23]:
'Z' < 'a'

True

In [14]:
'Apple' < 'apple'

True

In [28]:
'가' < 'z'

False

문자열에 `+` 와 `*` 연산자를 사용할 수 있다.

In [66]:
x1 = "하"
5*x1

'하하하하하'

In [67]:
x1 = "I"
x2 = "am"
x3 = "Tom"
x1 + ' ' + x2 + ' ' + x3

'I am Tom'

### 리스트와 행렬

- 리스트(`list`)는 여러 개의 원소(element)를 모아 놓은 순서가 있는 객체이며 `[]` 로 지정한다. 
- 행렬(`array`)은 **같은 형식의 원소들**을 모아 놓은 순서가 있는 객체이다. 행렬은 라이브러리 `numpy` 를 불러서 사용할 수 있다.
- 행렬 형식의 지정은  `np.array()` 사용
- 행렬을 만드는 함수
  + `np.array()`
  + `np.arange()`
  + `np.repeat()`

- 행렬의 차원을 변경하는 메소드 `reshape()`
- 행렬의 원소를 추출하는 방법: `array[row index, col index]`



**리스트나 행렬의 처음 위치(`index`)는 모두 0으로 시작한다!!!**

In [29]:
a1 = [1,2,3,4]
a1[0]

1

In [31]:
a1[1]

2

In [32]:
a1[3]

4

In [33]:
a1[4] # 오류! 리스트의 범위를 벗어난 경우 

IndexError: list index out of range

리스트는 서로 다른 형식의 자료를 모아놓을 수 있다. 

In [44]:
a1 = [1,"A",3, True]
a1

[1, 'A', 3, True]

In [45]:
a1[0]

1

In [46]:
a1[1]

'A'

In [47]:
a1[3]  

True

In [48]:
a2 = [1,2,a1,['A', 'B']]

In [49]:
a2[2]

[1, 'A', 3, True]

In [50]:
a2[3]

['A', 'B']

연산자 `in` 를 이용하여 왼쪽에 주어진  객체가  오른쪽의 리스트에 포함된 원소인지 참과 거짓을 구할 수 있다.

In [68]:
a1 = 1
a2 = [2]
a3 = [3,4]
a3 = [a1, a2, a3]

In [69]:
a3

[1, [2], [3, 4]]

In [70]:
1 in a3

True

In [71]:
2 in a3 # 숫자 2는 a3 의 원소가 아니다. 

False

In [72]:
[2] in a3 # 하나의 원소 2 호 구성된 리스트는 a3 안에 있다.

True

In [73]:
3 in a3

False

In [74]:
[3,4] in a3

True

라이브러이 `numpy` 의 행렬은 같은 형식의 자료만 모아놓을 수 있다.

In [53]:
x0 = np.array([1,"A",3, True])
x0 # 모든 원소가 문자열이 된다.

array(['1', 'A', '3', 'True'], dtype='<U21')

In [54]:
x1  = np.array([1,2,3,4])
x1

array([1, 2, 3, 4])

In [55]:
x1[0]

1

In [56]:
x1[0:2]

array([1, 2])

In [57]:
x2 = np.array([[1,2,3,4], [5,6,7,8]])
x2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [58]:
x2[0,0]

1

In [59]:
x2[0:2, 0:2]

array([[1, 2],
       [5, 6]])

In [60]:
x2[0, 1:3]

array([2, 3])

행렬에서 `reshape` 와 `arange` 를 사용하면 편리하게 다양한 행렬을 쉽게 만들 수 있다.

In [61]:
x3 = np.array([[1,2,3,4,5,6,7,8]])
x3

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [62]:
x3.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [77]:
y = np.arange(10)
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
a= np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
a= np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [82]:
a= np.arange(1,10,3)
a

array([1, 4, 7])

In [83]:
a= np.arange(1,11,3) 
a

array([ 1,  4,  7, 10])

In [86]:
y = np.arange(10)
y.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [88]:
y.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [87]:
y2 = np.arange(10).reshape(2,5) # 위의 두 표현식을 하나의 문장으로 구성할 수 있다.
y2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 데이터프레임

- 데이터프레임를 만드는 방법
- 데이터프레임의 열(들)을 선택하는 방법
- 데이터프레임을 조건으로 슬라이싱(slicing) 또는 부분 선택(subset) 하는 방법
  + 비교연산자 `<`, `<=`, `>`, `>=`, `!=`, `==` 을 사용한다.
  + 두 개 이상의 비교 표현식을 연결할 경우 또는(OR) 은 `|`을 사용하고 그리고(AND) 는 `&` 를 사용한다.
  + 비교 표현식을 연결할 경우 각 비교식은 언제나 괄호 `()` 로 묶어준다.
 
  + 라벨(label, 이름)에 기반한 인덱스

    + 데이타프레임의 열이름(column name)으로 지칭하거나 또는 행을 조건식을 이용한 True, False 로 선택할 때 사용한다.

    + 행과 열을 모두 슬라이싱 하는 경우 `.loc[]`을 사용한다. 열만 슬라이싱하는 경우도 `.loc[]` 사용 가능 

  + 위치(integer position)에 기반한 인덱스

    + 행과 열 순서의 위치를 나타내는 정수를 사용하여 슬라이싱한다.

    + 모든 위치는 0으로 시작한다.

    + `.iloc[]` 을 사용한다.  

- 정렬하는 방법: `df.sort_values()` 
- 열이름 바꾸는 방법: `df.rename()`
- 새로운 열의 생성
- 열과 행의 요약 (예: `df.sum(axis=0)`, `df.sum(axis=0)`)  
- 숫자 열의 요약 통계 : `df.describe()`
- 데이터프레임의 그룹화 
- 데이터프레임의 결합

  ```
  pd.merge(left_df, right_df, on="name", how="inner")
  ```
  + 이제 두 개의 데이터 프레임을 결합할 때 식별자를 선택하는 방법을 요약해 보자.

    + `how='left'` : 식별자는 왼쪽 데이터프레임에만 있는 것으로 선택
    + `how='right'` : 식별자는 오른쪽 데이터프레임에만 있는 것으로 선택
    + `how='inner'` : 식별자는 두 데이터프레임에 공통인 것으로 선택
    + `how='outer'` : 식별자는 두 데이터프레임에 나타난 모든 것으로 선택

  식별자를 선택하는 선택명령문 `how=` 을 지정하지 않으면 디폴트는 방법은 `how='inner` 이다.




In [89]:
df = pd.DataFrame(
    { 'name' : ['이철수', '김영희', '홍길동', 'John Smith', 'Mary Doe'],
      'sex'  : ['M', 'F', 'M', 'M', 'F'],
      'age'  : [ 23, 25, 21, 33, 45],
      'height' : [153.5, 175.3, 163.4, 180.0, 165.7]
    } )

In [90]:
df

name sex  age  height
0         이철수   M   23   153.5
1         김영희   F   25   175.3
2         홍길동   M   21   163.4
3  John Smith   M   33   180.0
4    Mary Doe   F   45   165.7

In [91]:
df.name

0           이철수
1           김영희
2           홍길동
3    John Smith
4      Mary Doe
Name: name, dtype: object

In [92]:
df['name'] # 결과는 시리즈(series)

0           이철수
1           김영희
2           홍길동
3    John Smith
4      Mary Doe
Name: name, dtype: object

In [93]:
df[['name']] # 결과는 데이터프레임(dataframe)

name
0         이철수
1         김영희
2         홍길동
3  John Smith
4    Mary Doe

In [94]:
df[['name', 'height']]

name  height
0         이철수   153.5
1         김영희   175.3
2         홍길동   163.4
3  John Smith   180.0
4    Mary Doe   165.7

In [95]:
df[df['sex'] == 'M']

name sex  age  height
0         이철수   M   23   153.5
2         홍길동   M   21   163.4
3  John Smith   M   33   180.0

In [96]:
df.loc[df['sex'] == 'M']  # df[df['sex'] == 'M'] 와 동일한 결과

name sex  age  height
0         이철수   M   23   153.5
2         홍길동   M   21   163.4
3  John Smith   M   33   180.0

In [97]:
df.loc[df['height'] >= 160.0]

name sex  age  height
1         김영희   F   25   175.3
2         홍길동   M   21   163.4
3  John Smith   M   33   180.0
4    Mary Doe   F   45   165.7

In [98]:
df.loc[df['height'] >= 160.0, ['name', 'height']]

name  height
1         김영희   175.3
2         홍길동   163.4
3  John Smith   180.0
4    Mary Doe   165.7

In [99]:
df[ (df['sex'] == 'M') & (df['height'] >= 160.0) ]

name sex  age  height
2         홍길동   M   21   163.4
3  John Smith   M   33   180.0

In [100]:
df.loc[ (df['age'] < 25 ) | (df['height'] >= 160.0) ]

name sex  age  height
0         이철수   M   23   153.5
1         김영희   F   25   175.3
2         홍길동   M   21   163.4
3  John Smith   M   33   180.0
4    Mary Doe   F   45   165.7

In [101]:
df.iloc[0,0]

'이철수'

In [102]:
df.iloc[0:2, 0:4]

name sex  age  height
0  이철수   M   23   153.5
1  김영희   F   25   175.3

In [103]:
df.sort_values(by ='age', ascending= True)

name sex  age  height
2         홍길동   M   21   163.4
0         이철수   M   23   153.5
1         김영희   F   25   175.3
3  John Smith   M   33   180.0
4    Mary Doe   F   45   165.7

In [104]:
df.sort_values(by ='height', ascending= False)

name sex  age  height
3  John Smith   M   33   180.0
1         김영희   F   25   175.3
4    Mary Doe   F   45   165.7
2         홍길동   M   21   163.4
0         이철수   M   23   153.5

In [105]:
df.rename( columns={ 'age' : '연령'})

name sex  연령  height
0         이철수   M  23   153.5
1         김영희   F  25   175.3
2         홍길동   M  21   163.4
3  John Smith   M  33   180.0
4    Mary Doe   F  45   165.7

In [106]:
df['height_inch'] = df['height'] * 39.3701  
df

name sex  age  height  height_inch
0         이철수   M   23   153.5   6043.31035
1         김영희   F   25   175.3   6901.57853
2         홍길동   M   21   163.4   6433.07434
3  John Smith   M   33   180.0   7086.61800
4    Mary Doe   F   45   165.7   6523.62557

키가 175 cm 이상인 사람들의 이름을 `평균이상` 으로 바꾸는 명령문

In [107]:
df.loc[ df.height >= 175, "name" ] = '평균이상'
df

name sex  age  height  height_inch
0       이철수   M   23   153.5   6043.31035
1      평균이상   F   25   175.3   6901.57853
2       홍길동   M   21   163.4   6433.07434
3      평균이상   M   33   180.0   7086.61800
4  Mary Doe   F   45   165.7   6523.62557

In [108]:
df[['age','height']].max()

age        45.0
height    180.0
dtype: float64

In [109]:
df[['age','height']].sum()

age       147.0
height    837.9
dtype: float64

In [110]:
df[['age','height']].mean()

age        29.40
height    167.58
dtype: float64

In [111]:
df[['age','height']].sum(axis=0)

age       147.0
height    837.9
dtype: float64

In [112]:
df[['age','height']].sum(axis=1)

0    176.5
1    200.3
2    184.4
3    213.0
4    210.7
dtype: float64

In [113]:
df.describe()

age      height  height_inch
count   5.000000    5.000000     5.000000
mean   29.400000  167.580000  6597.641358
std     9.838699   10.405623   409.670437
min    21.000000  153.500000  6043.310350
25%    23.000000  163.400000  6433.074340
50%    25.000000  165.700000  6523.625570
75%    33.000000  175.300000  6901.578530
max    45.000000  180.000000  7086.618000

In [114]:
grouped = df.groupby(by='sex')
grouped.mean()

age      height  height_inch
sex                                    
F    35.000000  170.500000  6712.602050
M    25.666667  165.633333  6521.000897

In [115]:
new = pd.DataFrame(
    { 'name' : ['이철수', '김영희', '홍길동', '고길동'],
      'weight' : [55.6, 67.1, 80.4, 64.4]
    } )
new

name  weight
0  이철수    55.6
1  김영희    67.1
2  홍길동    80.4
3  고길동    64.4

In [116]:
merged_inner = pd.merge(df, new, on ='name', how='inner')
merged_inner

name sex  age  height  height_inch  weight
0  이철수   M   23   153.5   6043.31035    55.6
1  홍길동   M   21   163.4   6433.07434    80.4

In [117]:
merged_outer = pd.merge(df, new, on ='name', how='outer')
merged_outer

name  sex   age  height  height_inch  weight
0       이철수    M  23.0   153.5   6043.31035    55.6
1      평균이상    F  25.0   175.3   6901.57853     NaN
2      평균이상    M  33.0   180.0   7086.61800     NaN
3       홍길동    M  21.0   163.4   6433.07434    80.4
4  Mary Doe    F  45.0   165.7   6523.62557     NaN
5       김영희  NaN   NaN     NaN          NaN    67.1
6       고길동  NaN   NaN     NaN          NaN    64.4

In [118]:
merged_left = pd.merge(df, new, on ='name', how='left')
merged_left

name sex  age  height  height_inch  weight
0       이철수   M   23   153.5   6043.31035    55.6
1      평균이상   F   25   175.3   6901.57853     NaN
2       홍길동   M   21   163.4   6433.07434    80.4
3      평균이상   M   33   180.0   7086.61800     NaN
4  Mary Doe   F   45   165.7   6523.62557     NaN

In [119]:
merged_right = pd.merge(df, new, on ='name', how='right')
merged_right

name  sex   age  height  height_inch  weight
0  이철수    M  23.0   153.5   6043.31035    55.6
1  김영희  NaN   NaN     NaN          NaN    67.1
2  홍길동    M  21.0   163.4   6433.07434    80.4
3  고길동  NaN   NaN     NaN          NaN    64.4